### ISSUE TITLE
GIS problem

### ISSUE THREAD

**Issue by 3vivekb** [codeforsanjose/renters-rights#66]
We need an API or dataset that we can call on to answer the following questions:
1) Does someone live within a City jurisdiction OR unincorporated SCC jurisdiction
2) Does someone live in a rent-controlled apartment, mobile home, or other unit, in San Jose
a) When was the building built _and_ occupied? Is it before September 7, 1979?
b) How many units are in the building? We need to know the individual numbers instead of aggregates: 2, 3, 4, or 5+ (this is because San Jose rent control policies are determined by 3+ units for ARO, and 4+ units for MHO).

*Zillow API*
Currently, the Zillow API only provides the following info:
- building information is sorted by multi-family 2-4 or 5+
- buildings that are built X year (no idea if it’s also _occupied_ same year it was built)

*SCC Property Info*
I have already asked Ky Le, Director of Office of Supportive Housing about figuring out the jurisdiction question, and he pointed me to sccpropertyinfo.org

Currently the Santa Clara County’s sccpropertyinfo.org tool doesn’t return all data or have a user friendly UI:
- When someone enters info, they have to separate the unit number from street name
- When someone enters info, they have to select type of street from dropdown, but the types are abnormal abbreviations, such as AV for avenue
- When I observed a user testing the site to find info about 544 Irving Ave, San Jose, they couldn’t find “AV”; instead they typed the street name + type into the street name section, and then the results returned NOT FOUND. When they finally figured out how to properly input the information to the form, the next page was a link to the property detail page in a table format. Next to the property link was “San Jose” for the respective city. This made the person think “This property is under the jurisdisction of the City of SJ”. They didn’t even notice the link to click and view the property detail page. Upon clicking the property detail page it was difficult to scan the page and find jurisdiction.
- When I tried searching for some other San Jose apartment buildings, it returned no results for 101 E San Fernando Street, which makes me think that the SCCpropertysearch website has incomplete information

*SJ Housing Dept*
Currently the City of San Jose Housing Department has a list of rent-controlled properties. This list is not complete it doesn’t include ALL rent controlled properties and some of the information may be inaccurate. There is about 5000+ properties in the spreadsheet. While Housing Dept is working on a rent registry, it is not clear _when_ it will be done. Housing Dept is rapidly expanding their staff this year and they have a lot to deal with policy proposals. They would also have to outreach to the community to get self reported information to build out the registry. That and some people have apprehension about it so there’s a lot of community buy in that will have to happen. I have a feeling it may be a year before there’s something up … I wouldn’t want to wait for it for this project. If there is public data we can tap tinto.  

I welcome your thoughts on approaching this problem, if you know someone at Santa Clara County that could provide this API, or data, or if there’s something internal that you have access to that we could tap?

**Comment by kphaneuf** [comment]
"Does someone live within a City jurisdiction OR unincorporated SCC jurisdiction?"
You can use these shapefiles to determine if someone lives in a city or unincorporated. Geocode the address and search for within either file.
http://gisdata2-sccplanning.opendata.arcgis.com/datasets/unincorporated-areas?geometry=-124.318%2C36.945%2C-119.091%2C37.71

http://gisdata2-sccplanning.opendata.arcgis.com/datasets/cities

"Does someone live in a rent-controlled apartment, mobile home, or other unit, in San Jose
a) When was the building built and occupied? Is it before September 7, 1979?
b) How many units are in the building? We need to know the individual numbers instead of aggregates: 2, 3, 4, or 5+ (this is because San Jose rent control policies are determined by 3+ units for ARO, and 4+ units for MHO)."
The assessor data that you can purchase includes when the building was built but only provides the year.  You could also tap into the city's permit system and pull the building and occupancy use permits to get specific dates.  The permit data should also have the units.  
Just a comment on the assessor data, the addresses are not accurate.  For example, VTA's River Oaks Admin Office's address is 3331 N 1st Street.  However, in the assessor role it was surveyed and recorded as 3333 N 1st Street.  I wouldn't use their data as a reliable address source.  The cities are individually putting together their address datasets and making them available to the public.  San Jose is currently working on updating theirs.  If you look at Milpitas they are a great example of what the future addresses will look like for each city with address points for each unit in a building.
http://services.arcgis.com/NkcnS0qk4w2wasOJ/ArcGIS/rest/services/SantaClaraCountyAddresses/FeatureServer
Good luck!

**Comment by easherma** [comment]
Would a different geocoder suffice or do you need specific data from Zillow?

**Comment by ychoy** [comment]
Closing this issue for now. We're no longer pursuing the address check feature. It is not feasible with the time and resources we have. Our team discussed and decided instead to pursue a wizard (based on input, direct user to a page with static content, without cross-referencing external data).
